version: '3.3'
services:
  redis:
    image: redis
    container_name: go-redis
    restart: always
    volumes:
      - /data/redis/data:/data
      - /data/redis/conf:/redis.conf:/usr/local/etc/redis/redis.conf
      - /data/redis/logs:/logs
    command:
      - redis-server
    ports:
      - '6379:6379'
  mysql:
    image: mysql:8.0
    container_name: go-mysql
    command:
      --max_connections=1000
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
    volumes:
      # 初始化数据库（注意脚本目录的相对位置）
      - ./script/:/docker-entrypoint-initdb.d
  web:
    container_name: gin-server
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    volumes:
      # 这个共享卷是用来存放配置文件。
      - ./config/:/app/config/
      # 该共享卷用来存储日志文件
      - ./logs/:/app/logs/
    ports:
      - '8080-8080'
